version: '3'

services:
  suno-api:
    build:
      context: .
      args:
        SUNO_COOKIE: ${SUNO_COOKIE}
    volumes:
      - ./public:/app/public
    ports:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.entrypoints=websecure
      - traefik.http.routers.${HASH}.tls.certResolver=letsencrypt
      - traefik.http.routers.${HASH}.rule=Host(`${SUNO_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${SUNO_PORT}